<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6f0e5c19273e081a3009d74a2fc0521b
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
        'D' => 
        array (
            'DVDoug\\BoxPacker\\Test\\' => 22,
            'DVDoug\\BoxPacker\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'DVDoug\\BoxPacker\\Test\\' => 
        array (
            0 => __DIR__ . '/..' . '/dvdoug/boxpacker/tests/Test',
        ),
        'DVDoug\\BoxPacker\\' => 
        array (
            0 => __DIR__ . '/..' . '/dvdoug/boxpacker/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6f0e5c19273e081a3009d74a2fc0521b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6f0e5c19273e081a3009d74a2fc0521b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
